spring:
  application:
    name: ${SPRING_APPLICATION_NAME:notification-service}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}
