spring:
  application:
    name: ${SPRING_APPLICATION_NAME:budget-api}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27018/orcamento}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}

springdoc:
  api-docs:
    path: ${SPRINGDOC_API_DOCS_PATH:/v3/api-docs}
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
    operations-sorter: ${SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER:method}
    tags-sorter: ${SPRINGDOC_SWAGGER_UI_TAGS_SORTER:alpha}

aws:
  region: ${AWS_REGION:us-east-1}
  endpoint: ${AWS_ENDPOINT:http://localhost:4566}
  access-key: ${AWS_ACCESS_KEY_ID:test}
  secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  sqs:
    budget-requests-queue: ${BUDGET_REQUESTS_QUEUE:budget-requests}
