spring:
  application:
    name: budget-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27018/orcamento}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

aws:
  region: ${AWS_REGION:us-east-1}
  endpoint: ${AWS_ENDPOINT:http://localhost:4566}
  access-key: ${AWS_ACCESS_KEY_ID:test}
  secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  sqs:
    budget-requests-queue: ${BUDGET_REQUESTS_QUEUE:budget-requests}
